# Generated by Django 4.1.5 on 2023-01-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_app1', '0003_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amt',
            new_name='amnt',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='catg',
            new_name='cag',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='daet',
        ),
    ]
